"""User link and food journal

Revision ID: 0009ed2c2550
Revises: b2feef82dbcd
Create Date: 2022-05-18 21:16:33.413804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0009ed2c2550'
down_revision = 'b2feef82dbcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bristol_scale',
    sa.Column('bristol_scale_id', sa.Integer(), nullable=False),
    sa.Column('bristol_scale_desc', sa.String(), nullable=True),
    sa.Column('bristol_scale_number', sa.Integer(), nullable=True),
    sa.Column('insert_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('bristol_scale_id')
    )
    op.create_table('journal_symptom',
    sa.Column('journal_symptom_id', sa.Integer(), nullable=False),
    sa.Column('journal_symptom_desc', sa.String(), nullable=True),
    sa.Column('insert_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('journal_symptom_id')
    )
    op.create_table('journal_symptom_severity',
    sa.Column('journal_symptom_sev_id', sa.Integer(), nullable=False),
    sa.Column('journal_symptom_sev_desc', sa.String(), nullable=True),
    sa.Column('insert_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('journal_symptom_sev_id')
    )
    op.create_table('user_link',
    sa.Column('user_link_id', sa.Integer(), nullable=False),
    sa.Column('app_user_id', sa.Integer(), nullable=False),
    sa.Column('combined_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('user_link_id')
    )
    op.create_table('user_symptom',
    sa.Column('user_symptom_id', sa.Integer(), nullable=False),
    sa.Column('app_user_id', sa.Integer(), nullable=False),
    sa.Column('journal_symptom_id', sa.Integer(), nullable=False),
    sa.Column('bristol_scale_id', sa.Integer(), nullable=True),
    sa.Column('user_symptom_date', sa.Date(), nullable=True),
    sa.Column('user_symptom_time', sa.Time(), nullable=True),
    sa.Column('user_symptom_datetime', sa.DateTime(), nullable=True),
    sa.Column('user_symptom_notes', sa.String(), nullable=True),
    sa.Column('insert_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['bristol_scale_id'], ['bristol_scale.bristol_scale_id'], ),
    sa.ForeignKeyConstraint(['journal_symptom_id'], ['journal_symptom.journal_symptom_id'], ),
    sa.PrimaryKeyConstraint('user_symptom_id')
    )
    op.create_table('journal_meal',
    sa.Column('journal_meal_id', sa.Integer(), nullable=False),
    sa.Column('app_user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('journal_meal_desc', sa.String(), nullable=True),
    sa.Column('eaten_date', sa.Date(), nullable=True),
    sa.Column('eaten_time', sa.Time(), nullable=True),
    sa.Column('eaten_datetime', sa.DateTime(), nullable=True),
    sa.Column('insert_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], ),
    sa.PrimaryKeyConstraint('journal_meal_id')
    )
    op.create_table('journal_ingredient',
    sa.Column('journal_ingredient_id', sa.Integer(), nullable=False),
    sa.Column('app_user_id', sa.Integer(), nullable=False),
    sa.Column('journal_meal_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('journal_ingredient_desc', sa.String(), nullable=True),
    sa.Column('eaten_date', sa.Date(), nullable=True),
    sa.Column('eaten_time', sa.Time(), nullable=True),
    sa.Column('eaten_datetime', sa.DateTime(), nullable=True),
    sa.Column('insert_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.ingredient_id'], ),
    sa.ForeignKeyConstraint(['journal_meal_id'], ['journal_meal.journal_meal_id'], ),
    sa.PrimaryKeyConstraint('journal_ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_ingredient')
    op.drop_table('journal_meal')
    op.drop_table('user_symptom')
    op.drop_table('user_link')
    op.drop_table('journal_symptom_severity')
    op.drop_table('journal_symptom')
    op.drop_table('bristol_scale')
    # ### end Alembic commands ###
