"""empty message

Revision ID: 0a127a8208c1
Revises: 8ff335c84fef
Create Date: 2020-08-18 20:13:08.527103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a127a8208c1'
down_revision = '8ff335c84fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'ingredient_measurement')
    op.alter_column('ingredient', sa.Column('ingredient_qty', sa.DECIMAL(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('ingredient_measurement', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('ingredient', sa.Column('ingredient_qty', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
