"""empty message

Revision ID: 1697fb1ff8c8
Revises: 
Create Date: 2020-08-23 16:53:39.762286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1697fb1ff8c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_username', sa.String(length=64), nullable=True),
    sa.Column('app_email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('insert_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_app_email'), 'app_user', ['app_email'], unique=True)
    op.create_index(op.f('ix_app_user_app_username'), 'app_user', ['app_username'], unique=True)
    op.create_table('recipe',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('recipe_name', sa.String(), nullable=True),
    sa.Column('recipe_desc', sa.String(), nullable=True),
    sa.Column('recipe_prep_time', sa.Integer(), nullable=True),
    sa.Column('recipe_cook_time', sa.Integer(), nullable=True),
    sa.Column('recipe_total_time', sa.Integer(), nullable=True),
    sa.Column('serving_size', sa.Integer(), nullable=True),
    sa.Column('diet_vegan', sa.Boolean(), nullable=True),
    sa.Column('diet_vegetarian', sa.Boolean(), nullable=True),
    sa.Column('diet_gluten', sa.Boolean(), nullable=True),
    sa.Column('meal_time', sa.String(), nullable=True),
    sa.Column('recipe_url', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('insert_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_table('current_meal',
    sa.Column('current_meal_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('app_user_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('active_ind', sa.Boolean(), nullable=True),
    sa.Column('insert_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], ),
    sa.PrimaryKeyConstraint('current_meal_id')
    )
    op.create_table('favorite_recipe',
    sa.Column('favorite_recipe_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('app_user_id', sa.Integer(), nullable=False),
    sa.Column('owner_ind', sa.Boolean(), nullable=True),
    sa.Column('insert_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], ),
    sa.PrimaryKeyConstraint('favorite_recipe_id')
    )
    op.create_table('ingredient',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_desc', sa.String(), nullable=True),
    sa.Column('insert_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], ),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_table('recipe_step',
    sa.Column('recipe_step_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('step_desc', sa.String(), nullable=True),
    sa.Column('insert_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], ),
    sa.PrimaryKeyConstraint('recipe_step_id')
    )
    op.create_table('user_recipe',
    sa.Column('user_recipe_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('app_user_id', sa.Integer(), nullable=False),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('owner_ind', sa.Boolean(), nullable=True),
    sa.Column('insert_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], ),
    sa.PrimaryKeyConstraint('user_recipe_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_recipe')
    op.drop_table('recipe_step')
    op.drop_table('ingredient')
    op.drop_table('favorite_recipe')
    op.drop_table('current_meal')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_app_user_app_username'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_app_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
