"""Changed combined_user_id to string

Revision ID: 221f585ac701
Revises: 0009ed2c2550
Create Date: 2022-05-19 09:45:59.073297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221f585ac701'
down_revision = '0009ed2c2550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_meal', sa.Column('combined_user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('current_meal', 'combined_user_id')
    # ### end Alembic commands ###
