"""empty message

Revision ID: 24b27c7a8bda
Revises: c14db75d04b4
Create Date: 2020-08-30 17:57:43.932951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b27c7a8bda'
down_revision = 'c14db75d04b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('meal_breakfast', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'meal_breakfast')
    # ### end Alembic commands ###
