"""empty message

Revision ID: 30c77562eda1
Revises: 
Create Date: 2019-08-24 19:33:20.609125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c77562eda1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('recipe_name', sa.String(), nullable=True),
    sa.Column('recipe_desc', sa.String(), nullable=True),
    sa.Column('recipe_prep_time', sa.Integer(), nullable=True),
    sa.Column('recipe_cook_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
