"""empty message

Revision ID: 3806f5102507
Revises: c59a377f93d5
Create Date: 2019-09-22 20:12:58.084173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3806f5102507'
down_revision = 'c59a377f93d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('serving_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'serving_size')
    # ### end Alembic commands ###
