"""empty message

Revision ID: 396d192909e8
Revises: 965ee7c19842
Create Date: 2020-09-19 23:15:52.653814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396d192909e8'
down_revision = '965ee7c19842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shopping_list', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shopping_list', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
