"""empty message

Revision ID: 3eae5d189df4
Revises: a3bef39b0c5b
Create Date: 2020-10-11 20:57:09.589485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eae5d189df4'
down_revision = 'a3bef39b0c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('recipe_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'recipe_deleted')
    # ### end Alembic commands ###
