"""Updated Shopping_List with combined_user_id

Revision ID: 5b2f4c1851db
Revises: 221f585ac701
Create Date: 2022-05-21 09:38:40.022536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2f4c1851db'
down_revision = '221f585ac701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list', sa.Column('combined_user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_list', 'combined_user_id')
    # ### end Alembic commands ###
