"""empty message

Revision ID: 64afd57a600d
Revises: b5bb4c971ff6
Create Date: 2019-09-02 13:55:15.737292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64afd57a600d'
down_revision = 'b5bb4c971ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_qty', sa.Integer(), nullable=True),
    sa.Column('ingredient_desc', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=True),
    sa.Column('step_desc', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steps')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
