"""empty message

Revision ID: 79347d407df8
Revises: 64afd57a600d
Create Date: 2019-09-08 21:47:18.243550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79347d407df8'
down_revision = '64afd57a600d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('ingredient_measurement', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'ingredient_measurement')
    # ### end Alembic commands ###
