"""empty message

Revision ID: 8e81852be74d
Revises: 3806f5102507
Create Date: 2019-09-22 22:28:54.865290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e81852be74d'
down_revision = '3806f5102507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_step', 'step_order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_step', sa.Column('step_order', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
