"""empty message

Revision ID: 8ff335c84fef
Revises: 89fb10df1532
Create Date: 2020-08-18 12:21:14.801594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff335c84fef'
down_revision = '89fb10df1532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('insert_datetime', sa.DateTime(), nullable=True))
    op.add_column('recipe', sa.Column('recipe_total_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'recipe_total_time')
    op.drop_column('recipe', 'insert_datetime')
    # ### end Alembic commands ###
