"""empty message

Revision ID: 965ee7c19842
Revises: 167a1e9595ea
Create Date: 2020-09-12 22:02:32.746548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965ee7c19842'
down_revision = '167a1e9595ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_step', sa.Column('step_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_step', 'step_order')
    # ### end Alembic commands ###
