"""empty message

Revision ID: 9703e2039439
Revises: 2e631a710b17
Create Date: 2020-07-30 20:12:17.022939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9703e2039439'
down_revision = '2e631a710b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('recipe_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'recipe_url')
    # ### end Alembic commands ###
