"""Added Google Sign-in columns

Revision ID: 9c4934c8500c
Revises: 3eae5d189df4
Create Date: 2022-03-30 20:40:01.939944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4934c8500c'
down_revision = '3eae5d189df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('google_authenticated', sa.Boolean(), nullable=True))
    op.add_column('app_user', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('app_user', sa.Column('native_authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'native_authenticated')
    op.drop_column('app_user', 'google_id')
    op.drop_column('app_user', 'google_authenticated')
    # ### end Alembic commands ###
