"""empty message

Revision ID: 9dbce11e2688
Revises: 396d192909e8
Create Date: 2020-09-20 12:10:21.499353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dbce11e2688'
down_revision = '396d192909e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list', sa.Column('ingredient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shopping_list', 'ingredient', ['ingredient_id'], ['ingredient_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_list', type_='foreignkey')
    op.drop_column('shopping_list', 'ingredient_id')
    # ### end Alembic commands ###
