"""new fields in user model

Revision ID: b2feef82dbcd
Revises: 9c4934c8500c
Create Date: 2022-05-01 11:17:00.663412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2feef82dbcd'
down_revision = '9c4934c8500c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'last_seen')
    # ### end Alembic commands ###
