"""empty message

Revision ID: b5b25e5d363b
Revises: ebba71946c05
Create Date: 2020-09-27 16:41:32.150307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b25e5d363b'
down_revision = 'ebba71946c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_error',
    sa.Column('error_id', sa.Integer(), nullable=False),
    sa.Column('app_user_id', sa.Integer(), nullable=True),
    sa.Column('insert_datetime', sa.DateTime(), nullable=True),
    sa.Column('error_val', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('error_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_error')
    # ### end Alembic commands ###
