"""empty message

Revision ID: c14db75d04b4
Revises: 1697fb1ff8c8
Create Date: 2020-08-30 17:56:23.520178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14db75d04b4'
down_revision = '1697fb1ff8c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('meal_dinner', sa.Boolean(), nullable=True))
    op.add_column('recipe', sa.Column('meal_lunch', sa.Boolean(), nullable=True))
    op.drop_column('recipe', 'meal_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('meal_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('recipe', 'meal_lunch')
    op.drop_column('recipe', 'meal_dinner')
    # ### end Alembic commands ###
