"""Added editor_certified column

Revision ID: c3db16fae5ed
Revises: 5b2f4c1851db
Create Date: 2022-05-22 21:03:42.038310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3db16fae5ed'
down_revision = '5b2f4c1851db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('editor_certified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'editor_certified')
    # ### end Alembic commands ###
