"""chef id

Revision ID: d6fb6a88fb03
Revises: 8c19368a3ead
Create Date: 2022-11-08 14:58:24.258864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6fb6a88fb03'
down_revision = '8c19368a3ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_meal', sa.Column('chef_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'current_meal', 'app_user', ['chef_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'current_meal', type_='foreignkey')
    op.drop_column('current_meal', 'chef_id')
    # ### end Alembic commands ###
